### ISSUE TITLE
See Participant Role ID

### ISSUE THREAD

**Issue by themak1985** [progressivetech/net.ourpowerbase.qrcodecheckin#23]
First - amazing plugin - thank you for making it.

Is there a way to see a participant's role ID when checking people in?

If they are an Attendee, Volunteer, Host, Speaker, etc?

Happy to hardcode it on our end, but would like some guidance, if possible.

**Comment by jmcclelland** [comment]
Sure, I would welcome a patch that does that. I think you'd just need to make small changes to `CRM/Qrcodecheckin/Page/QrcodecheckinLanding.php` and the corresponding template file in `templates/CRM/Qrcodecheckin/Page/QrcodecheckinLanding.tpl`. You should be able to see how the other fields are handled and would only need to add a line for the participant role.

**Comment by jmcclelland** [comment]
Fixed via https://github.com/progressivetech/net.ourpowerbase.qrcodecheckin/pull/24
