### ISSUE TITLE
Spelling mistake in Checkin.php

### ISSUE THREAD

**Issue by UeNu9** [progressivetech/net.ourpowerbase.qrcodecheckin#27]
In the file net.ourpowerbase.qrcodecheckin/api/v3/Qrcodecheckin/Checkin.php at line 45 there is a spelling mistake.
The line 45 says:
  $values = array_pop($results['values']);
but the variable $results does not exist there and should be $result instead.
Therefore the whole line has to be replaced by:
  $values = array_pop($result['values']);

This mistake results in the "Update to Attended" button not working (on the page linked in the QR code). It shows an error message and does not update the status.

**Comment by jmcclelland** [comment]
Thanks. Should be fixed now.
