### ISSUE TITLE
Does not appear to work when registering for another person

### ISSUE THREAD

**Issue by xpdientUK** [progressivetech/net.ourpowerbase.qrcodecheckin#36]
Have tested on registering another person and also on registering multiple participant. The code is not generated in the email.

**Comment by jmcclelland** [comment]
Thanks for the report - I haven't tested this option! I may not have time to fix this - but would welcome a patch.

**Comment by xpdientUK** [comment]
HI Jamie - my bad the module works as intended - and as documented which I had not paid enough attention to. I had assumed that there was a token you could just put into a scheduled reminder that was sent after registration but I can see that was my magical thinking. Super useful extension.
