### ISSUE TITLE
Is it possible to change permission from "Administer" to "CiviEvent"?

### ISSUE THREAD

**Issue by tapashdatta** [progressivetech/net.ourpowerbase.qrcodecheckin#5]
Hi Thanks for creating a very useful extension. Only concern I have is, we have lots of volunteers who would be scanning the QR code. To give them permission to "Administer" is a huge decision. Instead can we not just set the permission to administer CiviEvent? Just a suggestion!! Thanks again

**Comment by jmcclelland** [comment]
Unfortunately, I can't control that via the extension. I agree, it would be nice to be more limited. The only suggestion is that you create a special role that has Administer CiviCRM but does not have any other Admin permission.
