### ISSUE TITLE
Is there a chance to enable QR code for multiple events?

### ISSUE THREAD

**Issue by tapashdatta** [progressivetech/net.ourpowerbase.qrcodecheckin#6]
Is there a chance to enable QR code for multiple events?

**Comment by jmcclelland** [comment]
Yes, that would be useful, but would require some changes. Right now you can use the QR code token in a CiviMail message - and to my knowledge only contact level tokens are available in CiviMail. A contact level token has no idea which event to use. So if more than one events is enabled, it would not know which event to generate the token for (or perhaps could simply generate a token for all available events?).

To preserve this functionality, I think we would have to have dynamically generated tokens - one for every event that is enabled, then you could pick the right token when sending the email. But, I'm not even sure if it's possible to add dynamically generated tokens.

Or, we would restrict tokens to be used only with email sent to a group of participants, in which the relevant event is available. But then you couldn't send tokens via CiviMail, which seems like a bad idea.

So - I guess my answer is: I don't know!

**Comment by tapashdatta** [comment]
Thanks for reply. I guess dynamically generated code is best option of all. If you are able to investigate further we are willing to contribute towards it to make necessary changes, as long as cost is within our reach.

**Comment by jmcclelland** [comment]
Unfortunately, I'm not in a position to offer programming for hire, but would welcome a patch if you can find somebody to write the code.
