### ISSUE TITLE
Problem with transparent PNG background

### ISSUE THREAD

**Issue by davyrhys** [progressivetech/net.ourpowerbase.qrcodecheckin#8]
I installed the extension so I can send QR code URLs to event participants' mobile phones (using CiviSMS). Clicking the URL opens the QR Code image (png file) for scanning and works perfectly. Thanks!

However I experienced a hurdle in that the browser background on my Chrome and Brave browsers is black, and because the default QR Code image has a transparent background the QR Code was not visible.

I fixed this by editing qrcodecheckin.php to generate a jpg rather than png image.

**Comment by jmcclelland** [comment]
Oh wow, didn't think of that. I wonder if there's an option when generating the png to not make it transparent?

**Comment by davyrhys** [comment]
I found a transparency option in
/vendor/chillerian/php-qrcode/src/Traits/QROptionsTrait.php....


...

*DAVY IVINS*
T:  011 656 0946
C:  084 207 8148
davy.ivins@gmail.com

**Comment by jmcclelland** [comment]
Thanks for the feedback, we should be creating non-transparent pngs now.
